services:
  haproxy:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        HAPROXY_VERSION: "3.0-alpine"
    develop:
      watch:
      - path: ../
        ignore:
        - README.md
        - LICENSE.txt
        action: rebuild
    volumes:
      - $PWD/ja4.lua:/tmp/haproxy_ja4.lua
      - $PWD/docker/haproxy_docker.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - 127.0.0.1:6969:6969
