---

name: Lint

on:
  push:
    branches: [latest]
    paths:
      - '**.py'
      - '.github/workflows/lint.yml'
      - 'requirements_lint.txt'
      - '.pylintrc'
  pull_request:
    branches: [latest]
    paths:
      - '**.py'
      - '.github/workflows/lint.yml'
      - 'requirements_lint.txt'
      - '.pylintrc'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements_lint.txt >/dev/null

      - name: Running PyLint
        run: |
          pylint --version
          pylint --rcfile .pylintrc --recursive=y .
